{"level":"info","message":"InjectorJob: starting at 2014-04-05 16:57:22\n","timestamp":"2014-04-05T21:57:22.581Z"}
{"level":"info","message":"InjectorJob: Injecting urlDir: /tmp/seed.txt\n","timestamp":"2014-04-05T21:57:22.582Z"}
{"level":"error","message":"stderr: 2014-04-05 16:57:22.683 java[4620:1003] Unable to load realm info from SCDynamicStore\n","timestamp":"2014-04-05T21:57:22.685Z"}
{"level":"info","message":"InjectorJob: org.apache.gora.util.GoraException: java.lang.RuntimeException: org.apache.hadoop.hbase.ZooKeeperConnectionException: HBase is able to connect to ZooKeeper but the connection closes immediately. This could be a sign that the server has too many connections (30 is the default). Consider inspecting your ZK server logs for that error and then make sure you are reusing HBaseConfiguration as often as you can. See HTable's javadoc for more information.\n\tat org.apache.gora.store.DataStoreFactory.createDataStore(DataStoreFactory.java:167)\n\tat org.apache.gora.store.DataStoreFactory.createDataStore(DataStoreFactory.java:135)\n\tat org.apache.nutch.storage.StorageUtils.createWebStore(StorageUtils.java:75)\n\tat org.apache.nutch.crawl.InjectorJob.run(InjectorJob.java:221)\n\tat org.apache.nutch.crawl.InjectorJob.inject(InjectorJob.java:251)\n\tat org.apache.nutch.crawl.InjectorJob.run(InjectorJob.java:273)\n\tat org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)\n\tat org.apache.nutch.crawl.InjectorJob.main(InjectorJob.java:282)\nCaused by: java.lang.RuntimeException: org.apache.hadoop.hbase.ZooKeeperConnectionException: HBase is able to connect to ZooKeeper but the connection closes immediately. This could be a sign that the server has too many connections (30 is the default). Consider inspecting your ZK server logs for that error and then make sure you are reusing HBaseConfiguration as often as you can. See HTable's javadoc for more information.\n\tat org.apache.gora.hbase.store.HBaseStore.initialize(HBaseStore.java:127)\n\tat org.apache.gora.store.DataStoreFactory.initializeDataStore(DataStoreFactory.java:102)\n\tat org.apache.gora.store.DataStoreFactory.createDataStore(DataStoreFactory.java:161)\n\t... 7 more\nCaused by: org.apache.hadoop.hbase.ZooKeeperConnectionException: HBase is able to connect to ZooKeeper but the connection closes immediately. This could be a sign that the server has too many connections (30 is the default). Consider inspecting your ZK server logs for that error and then make sure you are reusing HBaseConfiguration as often as you can. See HTable's javadoc for more information.\n\tat org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.<init>(ZooKeeperWatcher.java:155)\n\tat org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getZooKeeperWatcher(HConnectionManager.java:1002)\n\tat org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.setupZookeeperTrackers(HConnectionManager.java:304)\n\tat org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:295)\n\tat org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:157)\n\tat org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:90)\n\tat org.apache.gora.hbase.store.HBaseStore.initialize(HBaseStore.java:109)\n\t... 9 more\nCaused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase\n\tat org.apache.zookeeper.KeeperException.create(KeeperException.java:90)\n\tat org.apache.zookeeper.KeeperException.create(KeeperException.java:42)\n\tat org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:809)\n\tat org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:837)\n\tat org.apache.hadoop.hbase.zookeeper.ZKUtil.createAndFailSilent(ZKUtil.java:903)\n\tat org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.<init>(ZooKeeperWatcher.java:133)\n\t... 15 more\n\n","timestamp":"2014-04-05T21:57:34.684Z"}
{"level":"info","message":"child process exited with code 255","timestamp":"2014-04-05T21:57:34.709Z"}
